version: '3'
services:

  api_service:
    build: .
    restart: always
    ports:
      - "8080:8080"    
    depends_on:
      - postgres_db
    networks:
      - default

  postgres_db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: kosavpa
      POSTGRES_DB: postgres
    networks:
      - default