spring:
  datasource:
    url: jdbc:h2:mem:KTEtest
    username: kosavpa
    password: pass
    driverClassName: org.h2.Driver

  h2:
    console:
      enabled: true

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

  liquibase:
    enabled: false